/* ============================================================
   CATEGORÍAS
   ------------------------------------------------------------
   Cada palabra es una tupla: [palabra, pista para el impostor]

   Reglas para escribir una pista:
   - Una o dos palabras, no más. Cuanto más se dice, más se
     delata: la idea es apenas un cable a tierra para poder
     bluffear, no una descripción.
   - Que no sea el rasgo único que solo esa cosa tiene (la trampa
     de "barro" para "hornero", que la define de una) ni un dato
     de enciclopedia, ni el nombre de una canción/apodo puntual si
     es una persona famosa.
   - No puede contener la palabra ni un sinónimo directo, ni una
     palabra que ya aparezca dentro del nombre de la palabra en sí.
   - Apunta al contexto, al clima o a la situación alrededor de la
     palabra, no a su definición.

   Para agregar una categoría nueva, copiá el bloque y sumalo
   al array. El `id` tiene que ser único (se usa para no repetir
   palabras dentro de la misma juntada).
   ============================================================ */

export const CATEGORIAS = [
  {
    id: "comida",
    nombre: "Comida y birra",
    palabras: [
      ["asado", "domingo"],
      ["choripán", "parado"],
      ["milanesa napolitana", "bodegón"],
      ["fernet con coca", "previa"],
      ["mate lavado", "ronda"],
      ["empanada salteña", "picante"],
      ["alfajor triple", "kiosco"],
      ["pizza de molde", "viernes"],
      ["locro", "olla"],
      ["dulce de leche", "pote"],
      ["sánguche de miga", "cumpleaños"],
      ["tortilla de papa", "sartén"],
      ["flan con dos", "postre"],
      ["medialuna de grasa", "desayuno"],
      ["helado de sambayón", "cucurucho"],
      ["chipá", "calentito"],
      ["torta frita", "lluvia"],
      ["guiso de lentejas", "caliente"],
      ["polenta", "salsa"],
      ["cordero", "campo"],
      ["asado a la estaca", "aire libre"],
      ["empanadas tucumanas", "fritas"],
      ["choripán con chimichurri", "calle"],
      ["milanesa a la napolitana", "papas"],
      ["fainá", "pizza"],
      ["sopa paraguaya", "horno"],
      ["tarta de ricota", "porciones"],
      ["pastelitos", "feria"],
      ["mate cocido", "caliente"],
      ["tereré", "fría"],
      ["ensalada rusa", "fiestas"],
      ["el vermú", "aceitunas"],
      ["morcipan", "feria"],
      ["pastafrola", "tarde"],
      ["tarta rogel", "confitería"],
      ["chocotorta", "cumpleaños"],
      ["alfajor de maicena", "mate"],
      ["sopa de verduras", "frío"],
      ["mondongo", "invierno"],
      ["bife a caballo", "sorpresa"],
      ["provoleta", "nunca falla"],
    ],
  },
  {
    id: "argentas",
    nombre: "Cosas muy argentas",
    palabras: [
      ["la SUBE sin saldo", "apuro"],
      ["el bondi lleno", "parado"],
      ["la cola en el banco", "espera"],
      ["cortar la calle", "enojo"],
      ["el paro de colectivos", "laburo"],
      ["la sobremesa eterna", "charla"],
      ["te llamo y arreglamos", "promesa"],
      ["el tío que arregla todo con alambre", "provisorio"],
      ["la escoba detrás de la puerta", "superstición"],
      ["el ventilador de pie", "calor"],
      ["la garrafa", "pesada"],
      ["el mantel de plástico", "trapo"],
      ["la funda del sillón", "cuidado"],
      ["el rollo de papel en la mesa", "práctico"],
      ["el mate amargo", "tradición"],
      ["el asado del domingo", "amigos"],
      ["el vuelto con caramelos", "monedas"],
      ["el colectivo que no pasa", "espera"],
      ["la cola del supermercado", "changuito"],
      ["el corte de luz", "verano"],
      ["la señora que barre la vereda", "chusmerío"],
      ["el perro que ladra toda la noche", "insomnio"],
      ["el vecino que toca el timbre", "inoportuno"],
      ["la heladera que hace ruido", "misterio"],
      ["el ascensor que se traba", "atrapado"],
      ["la fila del colectivo", "sol"],
      ["el semáforo que no funciona", "quilombo"],
      ["el tren lleno de gente", "presionado"],
      ["el piquete en la calle", "quejas"],
    ],
  },
  {
    id: "cancha",
    nombre: "Cancha y potrero",
    palabras: [
      ["el papi fútbol", "techo"],
      ["la pelota de trapo", "pobreza"],
      ["el VAR", "polémica"],
      ["el hincha con el bombo", "ruido"],
      ["el superclásico", "no termina bien"],
      ["el gol con la mano", "picardía"],
      ["el penal", "oportunidad"],
      ["la barrera con las manos abajo", "precaución"],
      ["el Mundial 2022", "diciembre"],
      ["el técnico del asado", "opinólogo"],
      ["los tapones del botín", "pasto"],
      ["la vuelta olímpica", "saludo"],
      ["el banderazo", "aliento"],
      ["falso 9", "mentiras"],
      ["el carrito de choripán", "afuera"],
      ["el hincha que se sube al alambrado", "euforia"],
      ["el gol de chilena", "1 en 1.000.000"],
      ["la pelota pinchada", "bicicleteria"],
      ["el cooling break", "publicidad"],
    ],
  },
  {
    id: "tv",
    nombre: "Cine y tv",
    palabras: [
      ["Esperando la Carroza", "clásico"],
      ["Relatos Salvajes", "venganza"],
      ["El Chavo", "risas"],
      ["Okupas", "under"],
      ["Los Simuladores", "disfraz"],
      ["El Marginal", "códigos"],
      ["Graduados", "reencuentro"],
      ["Casi Ángeles", "banda"],
      ["Floricienta", "niños"],
      ["Rebelde Way", "uniforme"],
      ["Gran Hermano", "telefe"],
      ["Showmatch", "sábados"],
      ["Los Simpsons", "almuerzo"],
      ["Titanic", "glaciar"],
      ["El Barro", "rejas"],
      ["El chavo del 8", "antiguo"],
      ["Casados con hijos", "argentina"],
    ],
  },
  {
    id: "lugares",
    nombre: "Lugares icónicos",
    palabras: [
      ["Mar del Plata", "verano"],
      ["Bariloche", "frío"],
      ["las Cataratas", "selva"],
      ["el Obelisco", "centro"],
      ["la Plaza de Mayo", "protesta"],
      ["el Tren de las Nubes", "altura"],
      ["Ushuaia", "sur"],
      ["Once", "comercial"],
      ["el Perito Moreno", "hielo"],
      ["la Ruta 40", "kilómetros"],
      ["la terminal de Retiro", "valijas"],
      ["Avellaneda (compras)","descuentos"],
      ["El Tigre","selva"],
      ["La Boca","colorido"],
      ["Puerto Madero","moderno"],
      ["el Riachuelo","barbijo"],
      ["el Planetario","espacio"],
      ["la Avenida 9 de Julio","anchura"],
      ["Cementerio de la Recoleta","estatuas"],
      ["el Teatro Colón","historia argentina"],
      ["Nueva York","parque"],
      ["Tokio","templos"],
      ["Grecia","islas"],
      ["Roma","antiguedad"],
      ["París","torre"],
      ["Islas Malvinas","reclamo"],
      ["Venezuela","complicado"],
      ["Favela","espacio reducido"],
      ["Colombia","café"],
      ["Bolivia","altiplano"],
      ["México","picante"],
      ["Brasil","carnaval"],
      ["Salta","cerro"],
      ["Microcentro","quilombo"],
    ],
  },
  {
    id: "juntadas",
    nombre: "Juntadas y fiestas",
    palabras: [
      ["la previa", "entrada en calor"],
      ["el after", "sol"],
      ["el karaoke", "música"],
      ["el cumple de 15", "festejo"],
      ["el casamiento", "planeado"],
      ["el bingo", "numeros"],
      ["la peña", "tradición"],
      ["el cotillón", "sombreros"],
      ["hacer vaquita", "junte"],
      ["el brindis con sidra", "burbuja"],
      ["el pan dulce", "festejos"],
      ["la piñata", "se rompe"],
      ["el hielo que nunca alcanza", "falta"],
    ],
  },
  {
    id: "bichos",
    nombre: "Bichos criollos",
    palabras: [
      ["carpincho", "tranquilo"],
      ["hornero", "madrugador"],
      ["ñandú", "rápido"],
      ["yaguareté", "manchado"],
      ["cuis", "roedor"],
      ["tero", "alerta"],
      ["benteveo", "canto"],
      ["coatí", "hocico"],
      ["guanaco", "andino"],
      ["llama", "cerros"],
      ["yacaré", "dientes"],
      ["cotorra", "bandada"],
      ["mosquito", "sangre"],
      ["pingüino", "temporada"],
      ["león", "macizo"],
      ["elefante", "miedoso"],
      ["tucán", "colorido"],
      ["toro", "cuernos"],
      ["castor", "árboles"],
      ["murciélago", "noche"],
      ["canguro", "con espacio"],
      ["salmón", "exclusivo"],
      ["ballena", "canta"],
      ["delfín", "juguetón"],
      ["salmón rosado", "lata"],
      ["ballena azul", "gigante"],
      ["caniche", "peludo"],
      ["vizcacha", "cuevas"],
      ["agua viva", "playa y mar"],
      ["langosta", "horno"],
      ["pulpo", "escurridizo"],
      ["cornalito", "comestible"],
    ],
  },
  {
    id: "oficios",
    nombre: "Oficios argentos",
    palabras: [
      ["el kiosquero", "esquina"],
      ["el verdulero", "en todos lados"],
      ["el remisero", "viaje"],
      ["el gasista matriculado", "papeles"],
      ["el mecánico de barrio", "ruidos"],
      ["el que vende garrapiñada", "carrito"],
      ["el heladero", "calor"],
      ["el cadete", "en movimiento"],
      ["el fletero", "fuerza"],
      ["el peluquero", "con turno"],
      ["el sodero", "envases"],
      ["el afilador de cuchillos", "antiguo"],
      ["el diariero", "madrugada"],
      ["el colectivero", "volante"],
      ["el plomero", "poca disponibilidad"],
      ["el churrero", "calor"],
      ["el que vende globos", "hilo"],
      ["el pintor", "enchastre"],
      ["el que vende algodón de azúcar", "nube"],
      ["el que vende pochoclo", "entretenimiento"],
      ["el parrillero de la esquina", "humo"],
    ],
  },
  {
    id: "dichos",
    nombre: "Dichos y frases",
    palabras: [
      ["estar en el horno", "complicado"],
      ["revolear la chancleta", "tradición"],
      ["sacarle la ficha", "lucidez"],
      ["mandar fruta", "verdulería"],
      ["irse al mazo", "no jugar"],
      ["estar hasta las manos", "pocas salidas"],
      ["hacer la plancha", "vagancia"],
      ["ponerse las pilas", "arranque"],
      ["tener calle", "experiencia"],
      ["hacerse el vivo", "ventajita"],
      ["quedar pagando", "vergüenza"],
      ["ser un chanta", "fanfarrón"],
      ["no tener un mango", "tener poco"],
    ],
  },
  {
    id: "famosos",
    nombre: "Personajes populares",
    palabras: [
      ["Maradona", "historia"],
      ["Messi", "orgullo"],
      ["Carlos Gardel", "sobrero"],
      ["Mirtha Legrand", "comida"],
      ["Susana Giménez", "diva"],
      ["Moria Casán", "picante"],
      ["Charly García", "piano"],
      ["Fito Páez", "Rosario"],
      ["Ricardo Fort", "mediático"],
      ["Marcelo Tinelli", "noventas"],
      ["Guillermo Francella", "comedia"],
      ["Ricardo Darín", "cine"],
      ["Tita Merello", "arrabal"],
      ["Sandro", "vintage"],
      ["Soda Stereo", "estadios"],
      ["Lali Espósito", "polémica"],
      ["Tini Stoessel", "pop"],
      ["Cacho Castaña", "romántico"],
      ["Dibu Martínez", "mundialista"],
      ["Paulo Londra", "Córdoba"],
      ["L-Gante", "viral"],
      ["Feid", "falsete"],
      ["Rauw Alejandro", "ochentoso"],
      ["Bad Bunny", "boricua"],
      ["Anuel AA", "tatuado"],
      ["Daddy Yankee", "retirado"],
      ["Nicky Jam", "jurado"],
      ["Wanda Nara", "polémicas"],
      ["Duki", "historia under"],
      ["Marley", "viajes"],
    ],
  },
];

/* El bolillero no tiene palabras propias: mezcla todas las demás. */
export const BOLILLERO = {
  id: "bolillero",
  nombre: "azar",
  nota: "mezcla de todas las categorías en una sola",
};
